package modelo.entidad;
// Generated 23/10/2020 04:17:46 PM by Hibernate Tools 4.3.1



/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private int ccEmpleado;
     private String nombreEmpleado;
     private String apellidoEmpleado;
     private String emailEmpleado;
     private String contrasenaEmpleado;
     private String telefonoEmpleado;
     private String direccionEmpleado;

    public Empleados() {
    }

    public Empleados(int ccEmpleado, String nombreEmpleado, String apellidoEmpleado, String emailEmpleado, String contrasenaEmpleado, String telefonoEmpleado, String direccionEmpleado) {
       this.ccEmpleado = ccEmpleado;
       this.nombreEmpleado = nombreEmpleado;
       this.apellidoEmpleado = apellidoEmpleado;
       this.emailEmpleado = emailEmpleado;
       this.contrasenaEmpleado = contrasenaEmpleado;
       this.telefonoEmpleado = telefonoEmpleado;
       this.direccionEmpleado = direccionEmpleado;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public int getCcEmpleado() {
        return this.ccEmpleado;
    }
    
    public void setCcEmpleado(int ccEmpleado) {
        this.ccEmpleado = ccEmpleado;
    }
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }
    
    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }
    public String getApellidoEmpleado() {
        return this.apellidoEmpleado;
    }
    
    public void setApellidoEmpleado(String apellidoEmpleado) {
        this.apellidoEmpleado = apellidoEmpleado;
    }
    public String getEmailEmpleado() {
        return this.emailEmpleado;
    }
    
    public void setEmailEmpleado(String emailEmpleado) {
        this.emailEmpleado = emailEmpleado;
    }
    public String getContrasenaEmpleado() {
        return this.contrasenaEmpleado;
    }
    
    public void setContrasenaEmpleado(String contrasenaEmpleado) {
        this.contrasenaEmpleado = contrasenaEmpleado;
    }
    public String getTelefonoEmpleado() {
        return this.telefonoEmpleado;
    }
    
    public void setTelefonoEmpleado(String telefonoEmpleado) {
        this.telefonoEmpleado = telefonoEmpleado;
    }
    public String getDireccionEmpleado() {
        return this.direccionEmpleado;
    }
    
    public void setDireccionEmpleado(String direccionEmpleado) {
        this.direccionEmpleado = direccionEmpleado;
    }




}


